### PR TITLE
Maxthread research

### LINKED ISSUE #216: Adjusting --maxThreads arg in Rhubarb in load testing
**Is this related to a problem? Please describe.**

We may be having a thread overload while running many Rhubarb instances. 

At the moment we are allowing Rhubarb too run on a maximum number of the threads. We should test to see if reducing the number of threads that Rhubarb occupies on each instance/request would increase the performance for concurrent requests. 

**Describe the solution you'd like**

Generate three tests in JMeter while adjusting the --maxThread arg in the Phoneme Factory for each test:
- 6 Requests @ 1 thread 
- 6 Requests @ half-max thread
- 6 Requests @ max-thread

Save results in a .csv file and generate some fun excel graphs! 

**Additional context**
 
If there are more efficient results by reducing the thread count we should consider changing the way Rhubarb performs thread assignment. 

A dynamic resolve could be to:

#of requests / maxNumber of Threads (or something like that)

BUT also I could be wrong and we might want to consider other solutions in increasing perfomance of our process

### PR DESCRIPTION
**Pull request by mkuelker**
Add max thread research to development.

### CODE REVIEW

**Review by vnajack — APPROVED** [review]
The reports you put together from the log files and illustrated in R really help us see the difference in performance. It's definitely worth checking this in a different environment rather than only on a local machine. I'd be interested to see if we could ask the client if their developer could test the performance at the end of February or maybe in March to see if the core test produces different results in a server setting.

Thanks for putting this together! It sheds light on this parameter :)

**Review by edouarde1 — APPROVED** [review]
Thanks Matt! It was really cool seeing all those graphs this morning. 

We should follow up next week. I think more testing would be useful especially seeing how things would behave with 100+ requests on a server with better performance.

**Comment by mkuelker** [comment]
Yeah for sure.  I'll look into it getting a quick n easy setup. 

Hopefully, everything we do testing on is windows though, otherwise, I may need to add some additional code.

**Comment by mkuelker** [comment]
Also I'll leave this branch undeleted for now, since I will likely be using it in the future

**Pull request merged**
