### PR TITLE
fixed ts config error and rhubarb error output

### LINKED ISSUE #130: TSConfig is failing and mystery error in Rhubarb proc
**Describe the bug**

1) TSConfig is having issues with babel.js file

2) Rhubarb proc is failing w/o a log

### PR DESCRIPTION
**Pull request by edouarde1**

### CODE REVIEW

**Review by LoganParker — APPROVED** [review]
Changes look great! Thank you!!

**Review by vnajack — APPROVED** [review]
Thank you for getting the bugfix out! I can confirm it fixed the issue!

**Comment by mkuelker** [comment]
Dear Edouard, 
This is a heartfelt comment about how wonderful your bugfix is. I am so proud of you, I feel like a proud dad who is not at all your dad. 
Love, 
Matthew

**Comment by edouarde1** [comment]
closes #130

**Pull request merged**
