### PR TITLE
created files for PT1 report

### LINKED ISSUE #151: Peer Testing Report (PDF) due Dec. 7
**Describe what needs to get done**
Based on your findings from the peer testing session, write up a report with the following information and submit it before the deadline:

- (10%) Brief description of your system and its current set of features available in the testing session
- (10%) Identify the number of participants that completed your study. In particular, include a table of participant's name, status (completed, partially completed, no show, type of evaluation (user vs. thinkaloud)). For incomplete and no show statuses, provide an explanation. Indicate who ran each session and who the participant was. (only for those that run the sessions remote) Links to all the videos that were recorded.
- (15%) The user group and associated list of tasks (use cases) you asked your participants to complete
- (20%) List of issues discovered, prioritized and presented in order of high, medium, then low.
- (20%) Average the quantitative scores you received from the participants in a bar graph with the 5 points on the y-axis and the 10 heuristics on the x-axis. Label your axes. Indicate the number of data points used in the graph. Be sure to explain the graph using the issues identified and any quoted comments you obtained from the participants.

**Describe the solution you'd like**
- each team member will upload their notes from their peer testing sessions
- each section of the report is split into separate .md files
- the sections will be amalgamated into a PDF to submit

**Additional context**
- our report might look a bit different from the breakdown provided because we did half the number of peer testing sessions so that we could also have a brainstorming session with the other teams, which we will need a section for as well

### LINKED ISSUE #152: Peer Testing Report - Section 1: System Description
**Describe what needs to get done**
- (10%) Brief description of your system and its current set of features available in the testing session
- part of #151 

**Describe the solution you'd like**
- markdown file that will eventually be amalgamated with the other sections

### LINKED ISSUE #153: Peer Testing Report - Section 2: Participants
**Describe what needs to get done**
- (10%) Identify the number of participants that completed your study. In particular, include a table of participant's name, status (completed, partially completed, no show, type of evaluation (user vs. thinkaloud)). For incomplete and no show statuses, provide an explanation. Indicate who ran each session and who the participant was. (only for those that run the sessions remote) Links to all the videos that were recorded.
- part of #151 

**Describe the solution you'd like**
- markdown file that will eventually be amalgamated with the other sections

### LINKED ISSUE #154: Peer Testing Report - Section 3: Task List
**Describe what needs to get done**
- (15%) The user group and associated list of tasks (use cases) you asked your participants to complete
- part of #151 

**Describe the solution you'd like**
- markdown file that will eventually be amalgamated with the other sections

### LINKED ISSUE #155: Peer Testing Report - Section 4: Issues Discovered
**Describe what needs to get done**
- (20%) List of issues discovered, prioritized and presented in order of high, medium, then low.
- part of #151 

**Describe the solution you'd like**
- markdown file that will eventually be amalgamated with the other sections

### LINKED ISSUE #156: Peer Testing Report - Section 5: Quantitative Scores
**Describe what needs to get done**
- (20%) Average the quantitative scores you received from the participants in a bar graph with the 5 points on the y-axis and the 10 heuristics on the x-axis. Label your axes. Indicate the number of data points used in the graph. Be sure to explain the graph using the issues identified and any quoted comments you obtained from the participants.
- part of #151 

**Describe the solution you'd like**
- markdown file that will eventually be amalgamated with the other sections

### LINKED ISSUE #157: Peer Testing Report - Section 6: Brainstorm Results
**Describe what needs to get done**
- our report might look a bit different from the breakdown provided because we did half the number of peer testing sessions so that we could also have a brainstorming session with the other teams, which we will need a section for as well
- part of #151 

**Describe the solution you'd like**
- markdown file that will eventually be amalgamated with the other sections

### PR DESCRIPTION
**Pull request by vnajack**
- Prepared Peer Testing I Report files
- created branch called `peer_testing_report` for us to use as a group for this report work
- included my notes from my single peer testing session on Wednesday, Nov. 30
- closes #151, 
- closes #152, 
- closes #153, 
- closes #154, 
- closes #155, 
- closes #156, 
- closes #157

### CODE REVIEW

**Comment by vnajack** [comment]
Learned how to convert PR to draft! Thanks @LoganParker

**Review by mkuelker — APPROVED** [review]
This looks great!

**Comment by vnajack** [comment]
We'll leave this as a draft until everyone gets their peer testing notes in, then we'll close this PR. We can open new ones once we get the report sections done.

**Comment by LoganParker** [comment]
@vnajack Considering the report was done in gdocs, should we just convert it to MD and then merge & close?

**Comment by vnajack** [comment]
Sorry, was super focused on my finals, so I wasn't focused here. Yes, I'll do that in the next couple days!

**Review by LoganParker — APPROVED** [review]

**Pull request merged**
