### PR TITLE
Add API Documentation

### LINKED ISSUE #260: Draft API Documentation
**Is this related to a problem? Please describe.**
We need documentation for our API if other developers are going to be using it

**Describe the solution you'd like**
Add a draft of API Documentation

### PR DESCRIPTION
**Pull request by mkuelker**
Add  API documentation to branch

### CODE REVIEW

**Comment by mkuelker** [comment]
I'm assuming what @edouarde1 set up follows the standard for a REST API? If not I can fix it before I merge. Also I guessed a little in some areas for what to include, let me know if it needs to be changed.

**Comment by vnajack** [comment]
@mkuelker I recommend removing the temp files 🙂

**Review by LoganParker — APPROVED** [review]
Looks good, I removed the tmp files from this as for some reason they were not removed, but would like to do a more in depth review later on

**Review by vnajack — APPROVED** [review]
I'd like to go over this at our next meeting after the break to make sure it has all the info it needs! Thank you for putting it together, Matt! It's great to have examples with explanations

**Pull request merged**
