### PR TITLE
Gantt chart update

### LINKED ISSUE #221: Update Gantt Chart for Feb 03
**Describe what needs to get done**
Update the Gantt chart to include issues completed, currently in progress, and future issues mentioned in our meetings.

**Describe the solution you'd like**
Update the Excel Gantt chart

### PR DESCRIPTION
**Pull request by vnajack**
Let me know if you guys want me to separate any of the issues to better show the timeline!

- updated Gantt chart branch from development
- closes #221

### CODE REVIEW

**Comment by vnajack** [comment]
converted to draft to help with the git workflow final updates

**Comment by edouarde1** [comment]
Thanks for the updates, can't see the file from here, but I know in class your were updating the chart frequently

Also I am glad the status checks worked up finally

**Review by edouarde1 — APPROVED** [review]

**Review by mkuelker — APPROVED** [review]
It's just a Gantt chart! What could possibly go wrong by adding it to the code base?
*Cue entire collapse of project*

Approved. 🥇

**Comment by mkuelker** [comment]
Also, thanks for keeping tabs on project development for all of us. 😄

**Comment by vnajack** [comment]
@edouarde1 Not sure if this is something we can change for the checks, but we got 2 approvals and it's still wanting the third person to check it. I tried unassigning Logan but it didn't work..

**Pull request merged**
