### PR TITLE
add anti aliasing to image script

### LINKED ISSUE #250: add anti ailiasing to images
**Is this related to a problem? Please describe.**
Images are kinda pixelated

**Describe the solution you'd like**
add anti aliasing to export script to help with this

### LINKED ISSUE #252: Refine blinking parameters
**Is this related to a problem? Please describe.**
There was a long and noticeable blink during the demo with the TA that seemed unnatural.

**Describe the solution you'd like**
Change the blinking parameters to improve realism so that long blinks are not noticeable. 

**Requirements for delivery**
Either (a) adjust parameters so that blinks cannot happen in the current nor the previous second, or (b) adjust the max time for blink frames.

### PR DESCRIPTION
**Pull request by LoganParker**
- closes #250 
- closes #252

### CODE REVIEW

**Review by vnajack — APPROVED** [review]
Good catch!

**Review by mkuelker — APPROVED** [review]
Nice Fix!

**Review by vnajack — APPROVED** [review]

**Comment by LoganParker** [comment]
> Good catch!

🎣

**Comment by vnajack** [comment]
Oh, I didn't realize this would end up in your PR. I thought it was already closed 🙈

**Comment by vnajack** [comment]
Decided... why stop there? Let's get the anti-aliasing in

**Comment by LoganParker** [comment]
> Oh, I didn't realize this would end up in your PR. I thought it was already closed 🙈

my bad! I should have closed, but closing it now as all looks good & we have the new images in!

**Comment by vnajack** [comment]
related to #253

**Pull request merged**
