### PR TITLE
Api'm sorry I kinda went on a deep dive and it got out of control

### LINKED ISSUE #59: Api Development Research
**Is this related to a problem? Please describe.**

Our group has had no experience designing and developing an API. It will be important for us to have a general idea of how we could tackle this early on rather than later. 

**Describe the solution you'd like**

A mini report that can answer some these questions and include the following information. 

- Does the API need to be constructed early on for this project ?
- What are the first steps in creating an API ? 
- A breakdown of the development required in creating an API 
- What services will be useful in hosting our API for testing purposes. 

**Describe the feature**
A clear and concise description of all requirements of this feature.

**What aspects are unclear - what needs to be done, or how it should be accomplished?**
Please describe - if you cannot describe, this should likely be a Task.

**Additional context**

### PR DESCRIPTION
**Pull request by LoganParker**
sickness really put me in a daze... but our code now runs as an API which is funky and fun? Sorry though not sure if people wanted to do this themselves or anything like that & im happy to walk everyone through everything I just got really really hyperfocused it was wild
- closes #59

### CODE REVIEW

**Comment by LoganParker** [comment]
We can now run our platform via Docker! See the readme for instructions.

Processing times when queuing 4 jobs (max before receiving **ECONNREFUSED** error) are as follows (In the order the jobs were run):
en-amber: 10min, 5.22s
fr-claude: 6min, 6.69s
jp-ayumi: 9min, 6.09s
en-amber: 10min, 3.06s

the following is the processing times for the same test when run on my local machine (M1 Mac):
en-amber: 47.37s
fr-claude: 8.09s
jp-ayumi: 13.12s
en-amber: 45.53s


I also found where the json files were being generated, and now clean them up. 

Some next steps:
- [ ] Update our packages.json file, to change certain packages so that we have dev dependencies and production dependencies correctly sorted out
- [ ] Determine what is causing the performance issue with the docker images
- [ ] Solve the ERRCONNREFUSED error that is popping up when we attempt to queue more than 4 jobs

**Comment by vnajack** [comment]
This is so great, thank you so much for getting this done over the break!

This is the initial PR for the API and it currently works, so you've got my approval. We can make more issues/tasks for improving it, so don't worry about trying to get it all done in this PR!

There seems to be a conflict with `index.ts` to check before we merge, though 👍

**Review by vnajack — APPROVED** [review]
- peer testing I preparations are being removed for development now that it's an API
- we might still be updating the Kukarella assets later, so the ones here are fine right now :)
- other API improvements and fixes can be brought up in separate issues and PRs, so don't worry about trying to fit it all in this one!

**Comment by LoganParker** [comment]
> This is so great, thank you so much for getting this done over the break!
> 
> This is the initial PR for the API and it currently works, so you've got my approval. We can make more issues/tasks for improving it, so don't worry about trying to get it all done in this PR!
> 
> There seems to be a conflict with `index.ts` to check before we merge, though 👍

Yeah, noticed that - its a pretty easy fix and I'm kinda confused as to why its even there, but I'll solve that once the reviews are done

**Review by edouarde1 — APPROVED** [review]
Thanks Logan for the API build. Will make more adjustments when we do more testing.

Great start to the semester!

**Pull request merged**
